### ISSUE TITLE
Unable starting application on Windows 8.1

### ISSUE THREAD

**Issue by timohermans** [blangslet/treasure-hunt#5]
I'm having trouble starting the application for the first time.

I've done 

```
    npm install
```

and

```
    bower install
```

But after

```
    ember server
```

I get the following message 

```
Livereload server on port 35729
Serving on http://0.0.0.0:4200/
undefined is not a function
TypeError: undefined is not a function
    at rimraf (D:\projects\treasure-hunt\node_modules\ember-cli\node_modules\broccoli-caching-writer
\node_modules\rimraf\rimraf.js:57:13)
    at lib$rsvp$node$$tryApply (D:\projects\treasure-hunt\node_modules\ember-cli\node_modules\brocco
li-caching-writer\node_modules\rsvp\dist\rsvp.js:1467:11)
    at lib$rsvp$node$$handleValueInput (D:\projects\treasure-hunt\node_modules\ember-cli\node_module
s\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1567:20)
    at fn (D:\projects\treasure-hunt\node_modules\ember-cli\node_modules\broccoli-caching-writer\nod
e_modules\rsvp\dist\rsvp.js:1555:18)
    at D:\projects\treasure-hunt\node_modules\ember-cli\node_modules\broccoli-caching-writer\index.j
s:100:14
    at lib$rsvp$$internal$$tryCatch (D:\projects\treasure-hunt\node_modules\ember-cli\node_modules\p
romise-map-series\node_modules\rsvp\dist\rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (D:\projects\treasure-hunt\node_modules\ember-cli\node_mod
ules\promise-map-series\node_modules\rsvp\dist\rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (D:\projects\treasure-hunt\node_modules\ember-cli\node_modules\pr
omise-map-series\node_modules\rsvp\dist\rsvp.js:472:11)
    at lib$rsvp$asap$$flush (D:\projects\treasure-hunt\node_modules\ember-cli\node_modules\promise-m
ap-series\node_modules\rsvp\dist\rsvp.js:1290:9)
    at process._tickCallback (node.js:355:11)
Cleanup error.
undefined is not a function
TypeError: undefined is not a function
    at Function.rimrafSync (D:\projects\treasure-hunt\node_modules\ember-cli\node_modules\broccoli-c
aching-writer\node_modules\rimraf\rimraf.js:262:13)
    at ConfigLoader.CachingWriter.cleanup (D:\projects\treasure-hunt\node_modules\ember-cli\node_mod
ules\broccoli-caching-writer\index.js:114:10)
    at cleanupTree (D:\projects\treasure-hunt\node_modules\ember-cli\node_modules\broccoli\lib\build
er.js:128:19)
    at D:\projects\treasure-hunt\node_modules\ember-cli\node_modules\promise-map-series\index.js:11:
14
    at lib$rsvp$$internal$$tryCatch (D:\projects\treasure-hunt\node_modules\ember-cli\node_modules\p
romise-map-series\node_modules\rsvp\dist\rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (D:\projects\treasure-hunt\node_modules\ember-cli\node_mod
ules\promise-map-series\node_modules\rsvp\dist\rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (D:\projects\treasure-hunt\node_modules\ember-cli\node_modules\pr
omise-map-series\node_modules\rsvp\dist\rsvp.js:472:11)
    at lib$rsvp$asap$$flush (D:\projects\treasure-hunt\node_modules\ember-cli\node_modules\promise-m
ap-series\node_modules\rsvp\dist\rsvp.js:1290:9)
    at process._tickCallback (node.js:355:11)
```

**Comment by timohermans** [comment]
Ah, updating ember-cli works:

```
npm install ember-cli --save-dev
```
